CREATE PROCEDURE spCadContato

	@NOME VARCHAR (50),
		@EMAIL VARCHAR (50),
			@CEL VARCHAR (50),
				@MSG VARCHAR (50) OUTPUT

AS
BEGIN

	IF EXISTS (SELECT * FROM CONTATOS WHERE EMAIL = @EMAIL)
	BEGIN
	SET @MSG = 'E-mail já cadastrado.'
	RETURN
	END

	ELSE
	BEGIN
	INSERT INTO CONTATOS (NOME, EMAIL, CEL) VALUES (@NOME, @EMAIL, @CEL)
	SET @MSG = 'Contato cadastrado.'
	RETURN
	END

END